let Name = prompt('Ismingizni Yozing?')
let surname = prompt('Familiyangizni Yozing?')
let age = prompt('Yoshingizni Yozing?')
let sex = prompt('Jinsingizni Yozing?')
let hobby = prompt('Hobbyingizni Yozing?')
let grade = prompt('Nechinchi sinfda oqiysiz?')
let married = prompt('Uylanganmisiz?')
let language = prompt('Qaysi tilarni bilasiz?')
let pet = prompt('Qanday uy hayvoningiz bor?')
let thing = prompt('Sizning yoqtirgan narsangiz?')
let itLanguage = prompt('Itni qaysi tillda yozasiz?')
let soda = prompt('Qanday gazli ichimliklar yoqadi?')
let fastFood = prompt('Sizning yoqtirgan fastfoodingiz qaysi?')
let streetFood = prompt('Sizning yoqtirgan kocha taomingiz?')
let homeFood = prompt('Sizning yoqtirgan uy taomingiz?')
let championsLeague = prompt('Qaysi jamoaga balet qilasiz?')
let marsId = prompt('Mars idingizni yozing?')
let marsParol = prompt('Mars parolingizni yozing?')
let trust = prompt('Siz bizga ishonasizmi?')
let number = prompt('Telefon nomeringizni yozing')

alert(Name + '<----------')
alert(surname + '<----------')
alert(age + '<----------')
alert(sex + '<----------')
alert(hobby + '<----------')
alert(grade + '<----------')
alert(married + '<----------')
alert(language + '<----------')
alert(pet + '<----------')
alert(thing + '<----------')
alert(itLanguage + '<----------')
alert(soda + '<----------')
alert(fastFood + '<----------')
alert(streetFood + '<----------')
alert(homeFood + '<----------')
alert(championsLeague + '<----------')
alert(marsId + '<----------')
alert(marsParol + '<----------')
alert(trust + '<----------')
alert(number + '<----------')